# Check out https://docs.codemagic.io/yaml/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_WORKSPACE: "flutterwebapp"
                XCODE_SCHEME: "flutterwebapp"
            xcode: latest
            cocoapods: default
        scripts:
            - flutter pub get
            - flutter build ios --release
        artifacts:
            - /Users/builder/clone/build/ios/iphoneos/Runner.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM